"""
Alembic: autogenerated migrations render `PydanticJSON` columns as plain JSON, and run.

The full-cycle test uses a real Alembic project in a temporary directory. Its `env.py` gets the
metadata through `config.attributes`, so the generated migration can't pick up any import of the
test models by accident.
"""

import shutil
from pathlib import Path
from typing import Any, Literal

import alembic
import pytest
import sqlalchemy as sa
from alembic import command
from alembic.autogenerate import produce_migrations, render_python_code
from alembic.autogenerate.api import AutogenContext
from alembic.config import Config
from alembic.migration import MigrationContext
from sqlalchemy.orm import DeclarativeBase, Mapped, Session, mapped_column

from sqlalchemy_pydantic_json import EmbeddedPydanticModel
from sqlalchemy_pydantic_json.alembic import make_render_item


class Address(EmbeddedPydanticModel):
    city: str = "Helsinki"


class Settings(EmbeddedPydanticModel):
    theme: str = "light"
    tags: set[str] = set()
    address: Address = Address()


class Base(DeclarativeBase):
    pass


class User(Base):
    __tablename__ = "users"
    id: Mapped[int] = mapped_column(primary_key=True)
    settings: Mapped[Settings] = mapped_column(Settings.column(), default=Settings)
    extra: Mapped[Settings | None] = mapped_column(Settings.column())


ENV_PY = """
from alembic import context
from sqlalchemy_pydantic_json.alembic import make_render_item

config = context.config
connection = config.attributes["connection"]
context.configure(
    connection=connection,
    target_metadata=config.attributes["metadata"],
    render_item=make_render_item(),
)
with context.begin_transaction():
    context.run_migrations()
"""


@pytest.fixture
def engine(tmp_path: Path) -> sa.Engine:
    return sa.create_engine(f"sqlite:///{tmp_path / 'app.db'}")


@pytest.fixture
def run_alembic(tmp_path: Path, engine: sa.Engine) -> Any:
    """Set up an Alembic project; return a function running a command against the database."""
    script_dir = tmp_path / "migrations"
    (script_dir / "versions").mkdir(parents=True)
    template = Path(alembic.__file__).parent / "templates" / "generic" / "script.py.mako"
    shutil.copy(template, script_dir / "script.py.mako")
    (script_dir / "env.py").write_text(ENV_PY)

    def run(fn: Any, *args: Any, **kwargs: Any) -> Any:
        config = Config()
        config.set_main_option("script_location", str(script_dir))
        with engine.begin() as connection:
            config.attributes["connection"] = connection
            config.attributes["metadata"] = Base.metadata
            return fn(config, *args, **kwargs)

    return run


def test_autogenerate_upgrade_check_downgrade(
    tmp_path: Path, engine: sa.Engine, run_alembic: Any
) -> None:
    run_alembic(command.revision, message="create users", autogenerate=True)
    [migration] = (tmp_path / "migrations" / "versions").glob("*.py")
    code = migration.read_text()

    # the migration uses plain JSON and imports neither this package nor the models
    assert "sa.Column('settings', sa.JSON(none_as_null=True), nullable=False)" in code
    assert "sa.Column('extra', sa.JSON(none_as_null=True), nullable=True)" in code
    assert "sqlalchemy_pydantic_json" not in code
    assert "PydanticJSON" not in code
    assert "tests" not in code

    run_alembic(command.upgrade, "head")
    with Session(engine) as s:
        s.add(User(id=1, settings={"tags": ["a"], "address": {"city": "Espoo"}}))
        s.commit()
    with Session(engine) as s:
        user = s.get(User, 1)
        assert user is not None
        assert user.settings.address.city == "Espoo"
        assert user.extra is None

    # an up-to-date database has no pending changes (compare_type is on by default)
    run_alembic(command.check)

    run_alembic(command.downgrade, "base")
    assert not sa.inspect(engine).has_table("users")


def render(metadata: sa.MetaData, render_item: Any = None, prefix: str = "sa.") -> str:
    """Render the migration that creates `metadata` from scratch."""
    with sa.create_engine("sqlite://").connect() as conn:
        context = MigrationContext.configure(conn)
        ops = produce_migrations(context, metadata).upgrade_ops
        assert ops is not None
        return render_python_code(ops, render_item=render_item, sqlalchemy_module_prefix=prefix)


def test_default_rendering_is_broken() -> None:
    # documents why the helper exists: without it, the migration can't run
    code = render(Base.metadata)
    assert "sqlalchemy_pydantic_json._model.PydanticJSON(none_as_null=True)" in code


def test_render_item_leaves_other_items_alone() -> None:
    code = render(Base.metadata, render_item=make_render_item())
    assert "sa.Column('id', sa.Integer(), nullable=False)" in code


def test_render_item_uses_the_configured_module_prefix() -> None:
    code = render(Base.metadata, render_item=make_render_item(), prefix="sqlalchemy.")
    assert "sqlalchemy.JSON(none_as_null=True)" in code


def test_render_item_wraps_user_function() -> None:
    seen: list[str] = []

    def mine(type_: str, obj: Any, autogen_context: AutogenContext) -> str | Literal[False]:
        seen.append(type_)
        if type_ == "type" and isinstance(obj, sa.Integer):
            return "sa.BigInteger()"
        return False

    code = render(Base.metadata, render_item=make_render_item(wrap=mine))
    assert "sa.Column('id', sa.BigInteger(), nullable=False)" in code  # user function applied
    assert "sa.Column('settings', sa.JSON(none_as_null=True)" in code  # ours applied
    assert "type" in seen


def test_passing_the_factory_itself_gives_a_clear_error() -> None:
    # render_item=make_render_item (without calling it): Alembic calls it with three arguments
    with pytest.raises(TypeError, match=r"Pass its result to Alembic"):
        render(Base.metadata, render_item=make_render_item)
